// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    if (defaultTargetPlatform case TargetPlatform.android) {
      return android;
    } else if (defaultTargetPlatform case TargetPlatform.iOS) {
      return ios;
    } else {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFiPDtqY1k6uGlU6lb2FUl5VEX-iiS7So',
    appId: '1:75714035386:android:bb01dd5febc967022c0c83',
    messagingSenderId: '75714035386',
    projectId: 'pasa-flutter',
    storageBucket: 'pasa-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1wUTGckW0x4labkokE1seuB7pKw9cFXs',
    appId: '1:75714035386:ios:e3b275b88bb76d442c0c83',
    messagingSenderId: '75714035386',
    projectId: 'pasa-flutter',
    storageBucket: 'pasa-flutter.appspot.com',
    iosBundleId: 'com.arnoodles.pasa',
  );
}
